# Generated by Django 5.1.2 on 2024-11-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.CharField(choices=[('transporte_auto', 'Auto'), ('transporte_publico', 'Publico')], max_length=30)),
                ('distancia', models.IntegerField()),
                ('energia', models.IntegerField()),
                ('dieta', models.CharField(choices=[('dieta_omnivora', 'Omnivora'), ('dieta_vegetariana', 'Vegetariana'), ('dieta_vegana', 'Vegana')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
    ]
